pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK17"
    }
    
    environment {
            cluster = 'vproapp-prod-rev'
            service = 'vprofileapptask-rev-service-bp4qgy9y'
    }

    stages {
        stage('Deploy to production'){
            steps {
                withAWS(credentials: 'awsrev', region: 'ap-south-1') {
                    sh('aws ecs update-service  --cluster ${cluster} --service ${service} --force-new-deployment')
                }
            }
        }
        }

    }
